### ISSUE TITLE
Error in Step-1: Missing gdal_calc.py during meteorological data processing

### ISSUE THREAD

**Issue by jamesYu365** [UW-SASWE/RAT#121]
I encountered an error while running the rat test command:

```rat test -d ./rat_prj/ -b GUNNISON -s ./rat_prj/params/secrets.ini```

The error message suggests that the gdal_calc.py command is missing:
```
2024-12-01 11:16:17 INFO:rat_basin>> Starting Step-1: Downloading and Pre-processing of meteorological data
2024-12-01 11:17:18 ERROR:rat_basin>> Error Executing Step-1: Downloading and Pre-processing of meteorological data
Traceback (most recent call last):
  File "/home/yubin/rat_prj/.rat_env/lib/python3.13/site-packages/rat/rat_basin.py", line 382, in rat_basin
    get_newdata(
    ~~~~~~~~~~~^
        basin_name= basin_name,
        ^^^^^^^^^^^^^^^^^^^^^^^
    ...<7 lines>...
        process= True
        ^^^^^^^^^^^^^
    )
    ^
  File "/home/yubin/rat_prj/.rat_env/lib/python3.13/site-packages/rat/data_processing/newdata.py", line 680, in get_newdata
    process_data(basin_bounds,raw_datadir, processed_datadir, startdate, enddate, secrets, temp_datadir)
    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yubin/rat_prj/.rat_env/lib/python3.13/site-packages/rat/data_processing/newdata.py", line 628, in process_data
    processed_statuses = dask.compute(*futures)
  File "/home/yubin/rat_prj/.rat_env/lib/python3.13/site-packages/dask/base.py", line 660, in compute
    results = schedule(dsk, keys, **kwargs)
  File "/home/yubin/rat_prj/.rat_env/lib/python3.13/site-packages/rat/data_processing/newdata.py", line 435, in process_precip
    run_command(cmd)
    ^^^^^^^^^^^
  File "/home/yubin/rat_prj/.rat_env/lib/python3.13/site-packages/rat/data_processing/newdata.py", line 30, in run_command
    res = subprocess.run(cmd, check=True, capture_output=True,shell=shell_bool)
      ^^^^^^^^^^^^^^^^^
  File "/home/yubin/rat_prj/.rat_env/lib/python3.13/subprocess.py", line 554, in run
    with Popen(*popenargs, **kwargs) as process:
      ^^^^^^^^^^^^^^^^^
  File "/home/yubin/rat_prj/.rat_env/lib/python3.13/subprocess.py", line 1036, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
    ^^^^^^^^^^^
  File "/home/yubin/rat_prj/.rat_env/lib/python3.13/subprocess.py", line 1966, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
    
FileNotFoundError: [Errno 2] No such file or directory: 'gdal_calc.py'
```
It seems that gdal_calc.py is required during Step-1 (Downloading and Pre-processing of meteorological data), but it is not found in my environment.

Could you please advise on how to resolve this issue? Do I need to install additional dependencies or modify the environment setup?

**Comment by SanchitMinocha** [comment]
It seems like gdal is missing in the environment. Did you do conda update or created a new environment for rat v 3.0.15?

**Comment by jamesYu365** [comment]
Thank you for your prompt response.

Yes, I updated my RAT version to v3.0.15. After that, I searched for any files containing gdal and found that the /rat_prj/.rat_env/lib/python3.13/site-packages/ directory does not have gdal. 

```
(base) yubin@zy-group:~/rat_prj/.rat_env$ find . -type f -iname "*gdal*"
./lib/libgdal.so.1.16.2
./lib/libgdal.la
./lib/libgdal.a
./lib/pkgconfig/gdal.pc
./lib/libgdal.so.36.3.10.0
./lib/cmake/gdal/GDALConfigVersion.cmake
./lib/cmake/gdal/GDALConfig.cmake
./lib/cmake/gdal/GDAL-targets-release.cmake
./lib/cmake/gdal/GDAL-targets.cmake
./lib/gdalplugins/gdal_HDF4.so
./lib/gdalplugins/gdal_HDF5.so
./lib/gdalplugins/gdal_netCDF.so
./bin/gdallocationinfo
./bin/gdalmdimtranslate
./bin/gdalmdiminfo
./bin/gdalbuildvrt
./bin/gdalinfo
./bin/gdal_rasterize
./bin/gdaladdo
./bin/gdalenhance
./bin/gdal_footprint
./bin/gdal-config
./bin/gdalmanage
./bin/gdalwarp
./bin/gdal_viewshed
./bin/gdal_grid
./bin/gdal_create
./bin/gdaltindex
./bin/gdaldem
./bin/gdalsrsinfo
./bin/gdal_translate
./bin/gdal_contour
./bin/gdaltransform
./include/gdal.h
./include/gdalpansharpen.h
./include/gdalgrid.h
./include/gdalcachedpixelaccessor.h
./include/gdalwarpkernel_opencl.h
./include/gdal_proxy.h
./include/gdal_mdreader.h
./include/gdalwarper.h
./include/gdal_rat.h
./include/gdal_alg.h
./include/gdal_priv.h
./include/gdalgrid_priv.h
./include/gdal_frmts.h
./include/gdal_pam.h
./include/gdal_csv.h
./include/gdal_vrt.h
./include/gdaljp2metadata.h
./include/gdal_alg_priv.h
./include/gdal_utils.h
./include/gdalgeorefpamdataset.h
./include/gdaljp2abstractdataset.h
./include/gdal_version.h
./include/gdal_simplesurf.h
./include/gdalsubdatasetinfo.h
./etc/conda/activate.d/gdal-activate.sh
./etc/conda/deactivate.d/gdal-deactivate.sh
./pkgs/libgdal-core-3.10.0-hef9eae6_2.conda
./pkgs/libgdal-hdf5-3.10.0-hefe6d7a_2.conda
./pkgs/libgdal-core-3.10.0-hef9eae6_2/lib/pkgconfig/gdal.pc
./pkgs/libgdal-core-3.10.0-hef9eae6_2/lib/libgdal.so.36.3.10.0
./pkgs/libgdal-core-3.10.0-hef9eae6_2/lib/cmake/gdal/GDALConfigVersion.cmake
./pkgs/libgdal-core-3.10.0-hef9eae6_2/lib/cmake/gdal/GDALConfig.cmake
./pkgs/libgdal-core-3.10.0-hef9eae6_2/lib/cmake/gdal/GDAL-targets-release.cmake
./pkgs/libgdal-core-3.10.0-hef9eae6_2/lib/cmake/gdal/GDAL-targets.cmake
./pkgs/libgdal-core-3.10.0-hef9eae6_2/bin/gdallocationinfo
./pkgs/libgdal-core-3.10.0-hef9eae6_2/bin/gdalmdimtranslate
./pkgs/libgdal-core-3.10.0-hef9eae6_2/bin/gdalmdiminfo
./pkgs/libgdal-core-3.10.0-hef9eae6_2/bin/gdalbuildvrt
./pkgs/libgdal-core-3.10.0-hef9eae6_2/bin/gdalinfo
./pkgs/libgdal-core-3.10.0-hef9eae6_2/bin/gdal_rasterize
./pkgs/libgdal-core-3.10.0-hef9eae6_2/bin/gdaladdo
./pkgs/libgdal-core-3.10.0-hef9eae6_2/bin/gdalenhance
./pkgs/libgdal-core-3.10.0-hef9eae6_2/bin/gdal_footprint
./pkgs/libgdal-core-3.10.0-hef9eae6_2/bin/gdal-config
./pkgs/libgdal-core-3.10.0-hef9eae6_2/bin/gdalmanage
./pkgs/libgdal-core-3.10.0-hef9eae6_2/bin/gdalwarp
./pkgs/libgdal-core-3.10.0-hef9eae6_2/bin/gdal_viewshed
./pkgs/libgdal-core-3.10.0-hef9eae6_2/bin/gdal_grid
./pkgs/libgdal-core-3.10.0-hef9eae6_2/bin/gdal_create
./pkgs/libgdal-core-3.10.0-hef9eae6_2/bin/gdaltindex
./pkgs/libgdal-core-3.10.0-hef9eae6_2/bin/gdaldem
./pkgs/libgdal-core-3.10.0-hef9eae6_2/bin/gdalsrsinfo
./pkgs/libgdal-core-3.10.0-hef9eae6_2/bin/gdal_translate
./pkgs/libgdal-core-3.10.0-hef9eae6_2/bin/gdal_contour
./pkgs/libgdal-core-3.10.0-hef9eae6_2/bin/gdaltransform
./pkgs/libgdal-core-3.10.0-hef9eae6_2/include/gdal.h
./pkgs/libgdal-core-3.10.0-hef9eae6_2/include/gdalpansharpen.h
./pkgs/libgdal-core-3.10.0-hef9eae6_2/include/gdalgrid.h
./pkgs/libgdal-core-3.10.0-hef9eae6_2/include/gdalcachedpixelaccessor.h
./pkgs/libgdal-core-3.10.0-hef9eae6_2/include/gdal_proxy.h
./pkgs/libgdal-core-3.10.0-hef9eae6_2/include/gdal_mdreader.h
./pkgs/libgdal-core-3.10.0-hef9eae6_2/include/gdalwarper.h
./pkgs/libgdal-core-3.10.0-hef9eae6_2/include/gdal_rat.h
./pkgs/libgdal-core-3.10.0-hef9eae6_2/include/gdal_alg.h
./pkgs/libgdal-core-3.10.0-hef9eae6_2/include/gdal_priv.h
./pkgs/libgdal-core-3.10.0-hef9eae6_2/include/gdalgrid_priv.h
./pkgs/libgdal-core-3.10.0-hef9eae6_2/include/gdal_frmts.h
./pkgs/libgdal-core-3.10.0-hef9eae6_2/include/gdal_pam.h
./pkgs/libgdal-core-3.10.0-hef9eae6_2/include/gdal_csv.h
./pkgs/libgdal-core-3.10.0-hef9eae6_2/include/gdal_vrt.h
./pkgs/libgdal-core-3.10.0-hef9eae6_2/include/gdaljp2metadata.h
./pkgs/libgdal-core-3.10.0-hef9eae6_2/include/gdal_alg_priv.h
./pkgs/libgdal-core-3.10.0-hef9eae6_2/include/gdal_utils.h
./pkgs/libgdal-core-3.10.0-hef9eae6_2/include/gdalgeorefpamdataset.h
./pkgs/libgdal-core-3.10.0-hef9eae6_2/include/gdaljp2abstractdataset.h
./pkgs/libgdal-core-3.10.0-hef9eae6_2/include/gdal_version.h
./pkgs/libgdal-core-3.10.0-hef9eae6_2/include/gdal_simplesurf.h
./pkgs/libgdal-core-3.10.0-hef9eae6_2/include/gdalsubdatasetinfo.h
./pkgs/libgdal-core-3.10.0-hef9eae6_2/etc/conda/activate.d/gdal-activate.sh
./pkgs/libgdal-core-3.10.0-hef9eae6_2/etc/conda/deactivate.d/gdal-deactivate.sh
./pkgs/libgdal-core-3.10.0-hef9eae6_2/share/man/man1/gdalbuildvrt.1
./pkgs/libgdal-core-3.10.0-hef9eae6_2/share/man/man1/gdalmdiminfo.1
./pkgs/libgdal-core-3.10.0-hef9eae6_2/share/man/man1/gdal_fillnodata.1
./pkgs/libgdal-core-3.10.0-hef9eae6_2/share/man/man1/gdal_rasterize.1
./pkgs/libgdal-core-3.10.0-hef9eae6_2/share/man/man1/gdalmanage.1
./pkgs/libgdal-core-3.10.0-hef9eae6_2/share/man/man1/gdal_edit.1
./pkgs/libgdal-core-3.10.0-hef9eae6_2/share/man/man1/gdal_polygonize.1
./pkgs/libgdal-core-3.10.0-hef9eae6_2/share/man/man1/gdalcompare.1
./pkgs/libgdal-core-3.10.0-hef9eae6_2/share/man/man1/gdal-config.1
./pkgs/libgdal-core-3.10.0-hef9eae6_2/share/man/man1/gdal_create.1
./pkgs/libgdal-core-3.10.0-hef9eae6_2/share/man/man1/gdal_merge.1
./pkgs/libgdal-core-3.10.0-hef9eae6_2/share/man/man1/gdalmove.1
./pkgs/libgdal-core-3.10.0-hef9eae6_2/share/man/man1/gdal_viewshed.1
./pkgs/libgdal-core-3.10.0-hef9eae6_2/share/man/man1/gdal_retile.1
./pkgs/libgdal-core-3.10.0-hef9eae6_2/share/man/man1/gdal_sieve.1
./pkgs/libgdal-core-3.10.0-hef9eae6_2/share/man/man1/gdaltindex.1
./pkgs/libgdal-core-3.10.0-hef9eae6_2/share/man/man1/gdallocationinfo.1
./pkgs/libgdal-core-3.10.0-hef9eae6_2/share/man/man1/gdal_translate.1
./pkgs/libgdal-core-3.10.0-hef9eae6_2/share/man/man1/gdalwarp.1
./pkgs/libgdal-core-3.10.0-hef9eae6_2/share/man/man1/gdal_pansharpen.1
./pkgs/libgdal-core-3.10.0-hef9eae6_2/share/man/man1/gdal_calc.1
./pkgs/libgdal-core-3.10.0-hef9eae6_2/share/man/man1/gdaldem.1
./pkgs/libgdal-core-3.10.0-hef9eae6_2/share/man/man1/gdaltransform.1
./pkgs/libgdal-core-3.10.0-hef9eae6_2/share/man/man1/gdal_footprint.1
./pkgs/libgdal-core-3.10.0-hef9eae6_2/share/man/man1/gdalsrsinfo.1
./pkgs/libgdal-core-3.10.0-hef9eae6_2/share/man/man1/gdal2tiles.1
./pkgs/libgdal-core-3.10.0-hef9eae6_2/share/man/man1/gdaladdo.1
./pkgs/libgdal-core-3.10.0-hef9eae6_2/share/man/man1/gdalinfo.1
./pkgs/libgdal-core-3.10.0-hef9eae6_2/share/man/man1/gdal_contour.1
./pkgs/libgdal-core-3.10.0-hef9eae6_2/share/man/man1/gdal_grid.1
./pkgs/libgdal-core-3.10.0-hef9eae6_2/share/man/man1/gdalmdimtranslate.1
./pkgs/libgdal-core-3.10.0-hef9eae6_2/share/man/man1/gdal_proximity.1
./pkgs/libgdal-core-3.10.0-hef9eae6_2/share/gdal/gdalicon.png
./pkgs/libgdal-core-3.10.0-hef9eae6_2/share/gdal/GDALLogoBW.svg
./pkgs/libgdal-core-3.10.0-hef9eae6_2/share/gdal/gdalmdiminfo_output.schema.json
./pkgs/libgdal-core-3.10.0-hef9eae6_2/share/gdal/GDALLogoGS.svg
./pkgs/libgdal-core-3.10.0-hef9eae6_2/share/gdal/gdalvrt.xsd
./pkgs/libgdal-core-3.10.0-hef9eae6_2/share/gdal/gdalinfo_output.schema.json
./pkgs/libgdal-core-3.10.0-hef9eae6_2/share/gdal/gdaltileindex.xsd
./pkgs/libgdal-core-3.10.0-hef9eae6_2/share/gdal/GDALLogoColor.svg
./pkgs/libgdal-core-3.10.0-hef9eae6_2/share/bash-completion/completions/gdalinfo
./pkgs/libgdal-hdf4-3.10.0-h380f24e_2.conda
./pkgs/libgdal-netcdf-3.10.0-hba670d9_2.conda
./pkgs/libgdal-netcdf-3.10.0-hba670d9_2/lib/gdalplugins/gdal_netCDF.so
./pkgs/libgdal-hdf5-3.10.0-hefe6d7a_2/lib/gdalplugins/gdal_HDF5.so
./pkgs/rasterio-1.4.2-py313ha085935_1/info/test/tests/test_gdal_raster_io.py
./pkgs/gdal-1.9.2-0.tar.bz2
./pkgs/libgdal-hdf4-3.10.0-h380f24e_2/lib/gdalplugins/gdal_HDF4.so
./pkgs/gdal-1.9.2-0/lib/libgdal.so.1.16.2
./pkgs/gdal-1.9.2-0/lib/libgdal.la
./pkgs/gdal-1.9.2-0/lib/libgdal.a
./pkgs/gdal-1.9.2-0/bin/gdallocationinfo
./pkgs/gdal-1.9.2-0/bin/gdalbuildvrt
./pkgs/gdal-1.9.2-0/bin/gdalinfo
./pkgs/gdal-1.9.2-0/bin/gdal_rasterize
./pkgs/gdal-1.9.2-0/bin/gdaladdo
./pkgs/gdal-1.9.2-0/bin/gdalenhance
./pkgs/gdal-1.9.2-0/bin/gdal-config
./pkgs/gdal-1.9.2-0/bin/gdalmanage
./pkgs/gdal-1.9.2-0/bin/gdalwarp
./pkgs/gdal-1.9.2-0/bin/gdal_grid
./pkgs/gdal-1.9.2-0/bin/gdaltindex
./pkgs/gdal-1.9.2-0/bin/gdaldem
./pkgs/gdal-1.9.2-0/bin/gdalsrsinfo
./pkgs/gdal-1.9.2-0/bin/gdal_translate
./pkgs/gdal-1.9.2-0/bin/gdal_contour
./pkgs/gdal-1.9.2-0/bin/gdaltransform
./pkgs/gdal-1.9.2-0/include/gdal.h
./pkgs/gdal-1.9.2-0/include/gdalgrid.h
./pkgs/gdal-1.9.2-0/include/gdalwarpkernel_opencl.h
./pkgs/gdal-1.9.2-0/include/gdal_proxy.h
./pkgs/gdal-1.9.2-0/include/gdalwarper.h
./pkgs/gdal-1.9.2-0/include/gdal_rat.h
./pkgs/gdal-1.9.2-0/include/gdal_alg.h
./pkgs/gdal-1.9.2-0/include/gdal_priv.h
./pkgs/gdal-1.9.2-0/include/gdal_frmts.h
./pkgs/gdal-1.9.2-0/include/gdal_pam.h
./pkgs/gdal-1.9.2-0/include/gdal_csv.h
./pkgs/gdal-1.9.2-0/include/gdal_vrt.h
./pkgs/gdal-1.9.2-0/include/gdaljp2metadata.h
./pkgs/gdal-1.9.2-0/include/gdal_alg_priv.h
./pkgs/gdal-1.9.2-0/include/gdal_version.h
./pkgs/gdal-1.9.2-0/share/gdal/gdalicon.png
./pkgs/gdal-1.9.2-0/share/gdal/GDALLogoBW.svg
./pkgs/gdal-1.9.2-0/share/gdal/GDALLogoGS.svg
./pkgs/gdal-1.9.2-0/share/gdal/gdal_datum.csv
./pkgs/gdal-1.9.2-0/share/gdal/GDALLogoColor.svg
./conda-meta/libgdal-netcdf-3.10.0-hba670d9_2.json
./conda-meta/libgdal-core-3.10.0-hef9eae6_2.json
./conda-meta/libgdal-hdf5-3.10.0-hefe6d7a_2.json
./conda-meta/libgdal-hdf4-3.10.0-h380f24e_2.json
./conda-meta/gdal-1.9.2-0.json
./share/man/man1/gdalbuildvrt.1
./share/man/man1/gdalmdiminfo.1
./share/man/man1/gdal_fillnodata.1
./share/man/man1/gdal_rasterize.1
./share/man/man1/gdalmanage.1
./share/man/man1/gdal_edit.1
./share/man/man1/gdal_polygonize.1
./share/man/man1/gdalcompare.1
./share/man/man1/gdal-config.1
./share/man/man1/gdal_create.1
./share/man/man1/gdal_merge.1
./share/man/man1/gdalmove.1
./share/man/man1/gdal_viewshed.1
./share/man/man1/gdal_retile.1
./share/man/man1/gdal_sieve.1
./share/man/man1/gdaltindex.1
./share/man/man1/gdallocationinfo.1
./share/man/man1/gdal_translate.1
./share/man/man1/gdalwarp.1
./share/man/man1/gdal_pansharpen.1
./share/man/man1/gdal_calc.1
./share/man/man1/gdaldem.1
./share/man/man1/gdaltransform.1
./share/man/man1/gdal_footprint.1
./share/man/man1/gdalsrsinfo.1
./share/man/man1/gdal2tiles.1
./share/man/man1/gdaladdo.1
./share/man/man1/gdalinfo.1
./share/man/man1/gdal_contour.1
./share/man/man1/gdal_grid.1
./share/man/man1/gdalmdimtranslate.1
./share/man/man1/gdal_proximity.1
./share/gdal/gdalicon.png
./share/gdal/GDALLogoBW.svg
./share/gdal/gdalmdiminfo_output.schema.json
./share/gdal/GDALLogoGS.svg
./share/gdal/gdal_datum.csv
./share/gdal/gdalvrt.xsd
./share/gdal/gdalinfo_output.schema.json
./share/gdal/gdaltileindex.xsd
./share/gdal/GDALLogoColor.svg
./share/bash-completion/completions/gdalinfo
```

I attempted to install gdal using mamba, but the system indicated that it was already installed. Subsequently, I used conda to install gdal.

However, after doing so, I encountered a new error message:

```
2024-12-01 13:59:53 ERROR:rat_basin>> Error in Configuration parameters defined to run RAT.
Traceback (most recent call last):
  File "/home/yubin/rat_prj/.rat_env/lib/python3.13/site-packages/rat/rat_basin.py", line 107, in rat_basin
    basins_shapefile = gpd.read_file(basins_shapefile_path)  # Reading basins_shapefile_path to get basin polygons and their attributes
  File "/home/yubin/rat_prj/.rat_env/lib/python3.13/site-packages/geopandas/io/file.py", line 278, in _read_file
    engine = _check_engine(engine, "'read_file' function")
  File "/home/yubin/rat_prj/.rat_env/lib/python3.13/site-packages/geopandas/io/file.py", line 124, in _check_engine
    _import_pyogrio()
    ~~~~~~~~~~~~~~~^^
  File "/home/yubin/rat_prj/.rat_env/lib/python3.13/site-packages/geopandas/io/file.py", line 77, in _import_pyogrio
    import pyogrio
  File "/home/yubin/rat_prj/.rat_env/lib/python3.13/site-packages/pyogrio/__init__.py", line 12, in <module>
    from pyogrio.core import (
    ...<14 lines>...
    )
  File "/home/yubin/rat_prj/.rat_env/lib/python3.13/site-packages/pyogrio/core.py", line 35, in <module>
    _init_gdal_data()
    ~~~~~~~~~~~~~~~^^
  File "pyogrio/_ogr.pyx", line 221, in pyogrio._ogr.init_gdal_data
ValueError: Found GDAL data directory at /home/yubin/rat_prj/.rat_env/share/gdal but it does not appear to correctly contain GDAL data files
```
It seems that GDAL is now installed, but there is an issue with the GDAL data directory. The directory /home/yubin/rat_prj/.rat_env/share/gdal exists, but it does not appear to contain the required GDAL data files.

Do you have any suggestions on how to resolve this? Any help would be greatly appreciated.

Thank you again!

**Comment by SanchitMinocha** [comment]
There seems to be an issue with the environment, possibly caused by the conda update command. Creating a new conda environment with Python and then installing RAT via conda using the conda-forge channel might resolve it.

**Comment by jamesYu365** [comment]
Apologies for the delay in my reply. I have deleted the old rat_project folder and reinstalled it. However, when initializing the environment using the command:
```
rat init -d ./rat_project/ -g
```
I encountered the following error:

```
Installed VIC successfully for RAT!
Downloading source code of routing model...
Failed to download routing model.
Traceback (most recent call last):
  File "/home/yubin/rat_project/.rat_env/bin/rat", line 10, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/yubin/rat_project/.rat_env/lib/python3.12/site-packages/rat/cli/rat_cli.py", line 552, in main
    args.func(args)
  File "/home/yubin/rat_project/.rat_env/lib/python3.12/site-packages/rat/cli/rat_cli.py", line 140, in init_func
    print(f"Installing VIC-Route using make in directory: {route_model}")
                                                           ^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'route_model' where it is not associated with a value
```
I was able to download the routing model previously, but now it fails with the above error. Could you confirm if there is an issue with the server, or if it might be related to my internet connection?

Thank you for your help!

**Comment by jamesYu365** [comment]
I was also wondering whether only Jason-3 is currently being used as the altimeter data source, and if there are any plans to incorporate additional altimeter satellite data into RAT in the future. Expanding the data sources could help improve the model's coverage and accuracy across different regions.

Thank you for considering this suggestion, and I look forward to hearing your thoughts.

**Comment by SanchitMinocha** [comment]
For future, I would recommend creating a new environment rather than deleting the entire project whenever there's an issue with the environment—this approach can save time and effort in the long run.

Regarding the error you encountered, it seems to be related to internet connectivity on your end, as I was unable to replicate it. For me, the routing code downloaded and installed successfully.

As for altimeter data, Jason-3 is currently the only supported altimeter in RAT. However, please note that while RAT allows downloading and extracting altimeter data, it does not yet use it for estimating outflow or storage changes. Consequently, its support in RAT is limited for now. In the future, we plan to incorporate SWOT elevation data as an additional data source pipeline into RAT.
